/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package optimizacion;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MAICK
 */
public final class Salida extends javax.swing.JFrame {

    TableModel modelo;
    //String[][] matriz;
    String titulo,variables,restricciones;
    JTable tablaSimplex, tablaSimplexM;
    
    
    
    public Salida(TableModel modelo, String titulo, String variables, String restricciones) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.modelo=modelo;
        this.variables=variables;
        this.restricciones=restricciones;
        
        this.labelTitulo.setText(titulo);
        this.labelVariables.setText(variables);
        this.labelRestricciones.setText(restricciones);
        
        //bandera para decidir que metodos visualizar
        boolean bandera=true;
        if(Integer.parseInt(variables)==2)
        {
            
        
            for (int i = 0; i < modelo.getRowCount(); i++) 
            {
                if(">=".equals( modelo.getValueAt(i, modelo.getColumnCount()-2) )  )
                {
                    bandera=false;
                    break;
                }
            }
            if(bandera)
            {
                Grafico grafico=new Grafico(modelo, Integer.parseInt(variables), Integer.parseInt(restricciones) );
                JSPGrafico.setViewportView(grafico.getContentPane());
                JPGrafico.add(JSPGrafico);
            }
        }
        if(!bandera)
        {
            visualizarSimplexM();
        }
        if(bandera)
        {
            visualizarSimplex();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonModificar = new javax.swing.JButton();
        botonMenu = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSimplex = new javax.swing.JPanel();
        jScrollPaneSimplex = new javax.swing.JScrollPane();
        panelSimplexM = new javax.swing.JPanel();
        jScrollPaneSimplexM = new javax.swing.JScrollPane();
        JPGrafico = new javax.swing.JPanel();
        JSPGrafico = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelVariables = new javax.swing.JLabel();
        labelRestricciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Programacion Lineal");

        jLabel2.setText("Titulo:");

        botonModificar.setText("Mirar/Modificar datos de entrada");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBotonVerDatosEntrada(evt);
            }
        });

        botonMenu.setText("Menú principal");
        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSalirMousePressed(evt);
            }
        });

        labelTitulo.setText("---------");

        javax.swing.GroupLayout panelSimplexLayout = new javax.swing.GroupLayout(panelSimplex);
        panelSimplex.setLayout(panelSimplexLayout);
        panelSimplexLayout.setHorizontalGroup(
            panelSimplexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimplexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSimplex, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSimplexLayout.setVerticalGroup(
            panelSimplexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimplexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSimplex, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Metodo Simplex", panelSimplex);

        javax.swing.GroupLayout panelSimplexMLayout = new javax.swing.GroupLayout(panelSimplexM);
        panelSimplexM.setLayout(panelSimplexMLayout);
        panelSimplexMLayout.setHorizontalGroup(
            panelSimplexMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimplexMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSimplexM, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSimplexMLayout.setVerticalGroup(
            panelSimplexMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimplexMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSimplexM, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Metodo Simplex - Tecnica de la M", panelSimplexM);

        javax.swing.GroupLayout JPGraficoLayout = new javax.swing.GroupLayout(JPGrafico);
        JPGrafico.setLayout(JPGraficoLayout);
        JPGraficoLayout.setHorizontalGroup(
            JPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSPGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        JPGraficoLayout.setVerticalGroup(
            JPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSPGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Metodo Grafico", JPGrafico);

        jLabel4.setText("Variables:");

        jLabel5.setText("Restricciones:");

        labelVariables.setText("N°");

        labelRestricciones.setText("N°");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(botonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jTabbedPane1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitulo)
                .addGap(101, 101, 101)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRestricciones)
                .addGap(125, 125, 125)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVariables)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelTitulo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(labelVariables)
                    .addComponent(labelRestricciones))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificar)
                    .addComponent(botonMenu)
                    .addComponent(botonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMousePressed
        System.exit( 0 ); 
    }//GEN-LAST:event_botonSalirMousePressed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        Menu menu=new Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_botonMenuActionPerformed

    private void clickBotonVerDatosEntrada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBotonVerDatosEntrada
        
        int columnas = modelo.getColumnCount(); 
        int filas = modelo.getRowCount();
        String[][] matrizG = new String[filas][columnas];
        for(int i=0; i<filas; i++) { 
        for(int j=0; j<columnas; j++) 
            matrizG[i][j]=String.valueOf(modelo.getValueAt(i,j));  
        }
        System.out.println("TERMINO MATRIZ");
        
        VentanaEntradaDatos VE=new VentanaEntradaDatos(titulo,
            Integer.parseInt(variables),Integer.parseInt(restricciones),matrizG);
        VE.setVisible(true);
        this.setVisible(false); 
        
    }//GEN-LAST:event_clickBotonVerDatosEntrada

    public void visualizarSimplex()
    {
        System.out.println("Click en el tabpanel");

        SimplexM simplex=new SimplexM(modelo, Integer.parseInt(variables), Integer.parseInt(restricciones) );
        System.out.println("SALIO DEL CONSTRUCTOR");

        this.tablaSimplex = new JTable(simplex.getModelTabla()){
            public boolean isCellEditable(int fila, int columna)
            {
                return false;
            }
        };
        this.tablaSimplex.setAutoResizeMode(0);
        this.tablaSimplex.setCellSelectionEnabled(false);

        TableColumnModel columnModel = this.tablaSimplex.getColumnModel();
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setPreferredWidth(100);
        }

        jScrollPaneSimplex.setViewportView(this.tablaSimplex);
        
        //////////////////////////////////////////////////////////////////////////////      
        
    }
    
    public void visualizarSimplexM()
    {
        SimplexM simplexM=new SimplexM(modelo, Integer.parseInt(variables), Integer.parseInt(restricciones) );
        
        this.tablaSimplexM = new JTable(simplexM.getModelTabla())
        {
            
            public boolean isCellEditable(int fila, int columna)
            {
                return false;
            }
        };
        
        this.tablaSimplexM.setAutoResizeMode(0);
        this.tablaSimplexM.setCellSelectionEnabled(false);

        TableColumnModel columnModel2 = this.tablaSimplexM.getColumnModel();
        for (int i = 0; i < columnModel2.getColumnCount(); i++) {
            columnModel2.getColumn(i).setPreferredWidth(100);
        }

        jScrollPaneSimplexM.setViewportView(this.tablaSimplexM);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            //new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPGrafico;
    private javax.swing.JScrollPane JSPGrafico;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPaneSimplex;
    private javax.swing.JScrollPane jScrollPaneSimplexM;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelRestricciones;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVariables;
    private javax.swing.JPanel panelSimplex;
    private javax.swing.JPanel panelSimplexM;
    // End of variables declaration//GEN-END:variables
}
